# MRF (Matrix for Reusable Workflows)
#  Represents the minimal case:
#  - one job in reusable workflow
name: MRF Regression Minimal

on:
  push:
    paths:
      - '**/sanity-runs.md'
  workflow_dispatch:

jobs:
  ReusableWorkflow:
    uses: ./.github/workflows/mrf-reusable-minimal.yml
    with:
      runson: ubuntu-latest
      env: regression